name: Update Data Daily

on:
  schedule:
    - cron: '0 1 * * *' # Se ejecuta todos los días a la 01:00 AM UTC.

jobs:
  download_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.14'

    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download data
      run: |
        python scripts/download_data.py

  preprocess_data:
    runs-on: ubuntu-latest
    needs: download_data
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.14'

    - name: Restore pip cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    - name: Preprocess data
      run: |
        python scripts/preprocess.py

  commit_and_push:
    runs-on: ubuntu-latest
    needs: preprocess_data
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config user.name "Lucas Carmusciano [GitHub Actions]"
        git config user.email "lucascarmusciano@gmail.com"

    - name: Commit and Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Daily data update"
        commit_author: lucascarmu
