name: Retrain Model

on:
  schedule:
    - cron: '0 3 */15 * *' # Runs at 03:00, every 15 days.
    
jobs:
  train_model:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.14'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model
      run: |
        python scripts/train.py

    - name: Evaluate model
      run: |
        python scripts/evaluate.py

    - name: Commit and Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update model
        commit_user_name: Lucas Carmusciano [GitHub Actions]
        commit_user_email: lucascarmusciano@gmail.com
        commit_author: lucascarmu